const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // Your HTML content with corrected closing tags and inline SVG
  const quillHtmlContent = `
    <style>
      a { text-decoration: none; }
      .h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 { line-height: 1; }
      h1 { font-weight: 100; font-size: 1.5em; }
      h2 { font-weight: 100; font-size: 1.2em; }
      h3 { font-weight: 100; font-size: 1em; }
      h4 { font-weight: 100; font-size: 0.8em; }
      h5 { font-weight: 100; font-size: 0.6em; }
      h6 { font-weight: 100; font-size: 0.5em; }
      .ql-font-serif { font-family: Georgia, Times New Roman, serif; }
      .ql-font-monospace { font-family: Monaco, Courier New, monospace; }
      .ql-size-small { font-size: 0.75em; }
      .ql-size-large { font-size: 1.5em; }
      .ql-size-huge { font-size: 2.5em; }
      .ql-direction-rtl { direction: rtl; text-align: inherit; }
      .ql-align-center { text-align: center; }
      .ql-align-justify { text-align: justify; }
      .ql-align-right { text-align: right; }
    </style>

   <h2><span class="ql-size-large sans-serif">But in the weeks since Vice President Kamala Harris ascended the 2024 Democratic ticket, she has mentioned climate change only in passing, and offered no specifics on how she would curb dangerous levels of warming. Climate leaders say they are fine with that.</span></h2>

<svg class='ql-size-large sans-serif' xmlns="http://www.w3.org/2000/svg" width="200" height="50">
  <text x="0" y="30" font-size="30" font-weight="100" fill="black">
    dangerous
  </text>
</svg>

  `;

  // Clean up any unnecessary <br> tags if needed
  let cleanedContent = quillHtmlContent.replace(/<br\s*\/?>/g, '');

  // Set the content of the page to the HTML generated by Quill.js
  await page.setContent(cleanedContent);

  // Generate PDF
  await page.pdf({
    path: 'output.pdf',
    format: 'A4',
    margin: {
      top: '1.9cm',
      left: '1.9cm',
      right: '1.32cm',
      bottom: '1.67cm'
    }
  });

  await browser.close();
})();
