import React from 'react'

const LoadingPages = () => {
     return (
          <div className='w-screen flex mx-auto flex-wrap place-content-center'>
               <div className='gap-20 w-fit mx-auto flex flex-wrap place-content-center'>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none w-44 md:w-52 h-60 cursor-wait bg-gray-100 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
               </div>
          </div>
     )
}

export default LoadingPages;