import React from 'react'

const LoadingPages = () => {
     return (
          <div className='w-screen flex mx-auto flex-wrap place-content-center'>
               <div className='w-fit mx-auto flex flex-wrap place-content-center'>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='hidden md:block select-none rounded-lg w-36 h-48 m-3 cursor-wait bg-gray-500 p-4 text-gray-800 relative overflow-hidden blur-[2px]'>
                         <span className='text-red-400'>---- </span> <span className='text-green-400'>-- </span> <span className='text-blue-400'>-- </span> <span className='text-yellow-400'>--- </span> <span className='text-teal-400'>--- </span> <span className='text-purple-950'>--- </span> <span className='text-pink-900'>--- </span> -- <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> <span className='text-green-400'>--- </span> -- - -- - <span className='text-green-400'>--- </span> -- <span className='text-black font-bold'>------- </span> <span className='text-yellow-800 font-thin'>---- </span> <span className='text-emerald-800 font-thin'>---- </span> -- -- <br />-- -- --- -- --- --- ---- - _
                         <div className='gradient-background animatedBlock h-full w-5 absolute top-0 z-20'></div>
                    </div>
                    <div className='p-5 place-content-center items-center flex flex-col space-y-5 absolute backdrop-blur-[2px] top-1/2 ml-1/2 lg:left-[40%] z-20'>
                         <div className='animate-spin border-[15px] border-l-red-700 border-y-red-700 w-24 h-24 rounded-full'></div>
                         <div className='text-2xl font-semibold text-gray-900'>Getting Your Pages</div>
                    </div>
               </div>
          </div>
     )
}

export default LoadingPages;